services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: spurro
      POSTGRES_PASSWORD: spurro
      POSTGRES_DB: spurro
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

  ansible:
    build: ./infrastructure/ansible
    # Must be in sync with:
    # infrastructure/src/common/constants/docker/DOCKER_IMAGE_WITH_ANSIBLE.ts
    image: spurro/ansible:local
    profiles: ["build"]

volumes:
  postgres_data:
  redis_data:
