#!/bin/sh
set -eu

# Apply AmneziaWG peers. Reads "PUBLIC_KEY PRESHARED_KEY CLIENT_IP" from stdin, one peer per
# line — never as arguments, so the preshared key does not show up in the node's process list.
# Keys and addresses are generated by @spurro/infrastructure; this script only registers what
# it is given, in the running interface and in the configuration file, under a single lock.
#
# Idempotent by design: re-applying a peer that is already present is how a rebuilt node is
# restored from the application database. File layout and interface come from the image ENV.
#
# All-or-nothing: every rejection lives in the read-only checks below, all inside the lock
# and all before the first awg set. The apply loop at the bottom never exits on its own — a
# batch that starts applying finishes.

PEERS_FILE=$(mktemp)
trap 'rm -f "$PEERS_FILE"' EXIT
cat > "$PEERS_FILE"
[ -s "$PEERS_FILE" ] || exit 0

exec 9>"${CONFIGURATION_FILE}.lock"
flock -x 9

# Line shape, and conflicts between lines of the batch itself: the live-state checks below
# cannot see those — neither peer of a conflicting pair is applied yet while they run — and
# the apply loop is not allowed to, so an in-batch duplicate would otherwise replay the very
# reassignment scenarios the live checks reject.
awk '
  NF == 0 { next }
  NF != 3 {
    print "Malformed peer line (expected PUBLIC_KEY PRESHARED_KEY CLIENT_IP); refusing to apply" > "/dev/stderr"
    exit 1
  }
  $3 in ip_owner && ip_owner[$3] != $1 {
    print "Client IP " $3 " is claimed by two peers in the same batch; refusing to apply" > "/dev/stderr"
    exit 1
  }
  $1 in peer_line && peer_line[$1] != $2 SUBSEP $3 {
    print "Peer " $1 " appears twice in the batch with different settings; refusing to apply" > "/dev/stderr"
    exit 1
  }
  { ip_owner[$3] = $1; peer_line[$1] = $2 SUBSEP $3 }
' "$PEERS_FILE"

# awg set silently reassigns an allowed IP that another peer already owns, which would
# strand the previous peer in the configuration file with a duplicate AllowedIPs block.
awg show "$INTERFACE" allowed-ips | awk -v peers_file="$PEERS_FILE" '
  { for (i = 2; i <= NF; i++) owner[$i] = $1 }
  END {
    while ((getline line < peers_file) > 0) {
      if (split(line, field, " ") != 3) continue
      if (field[3] "/32" in owner && owner[field[3] "/32"] != field[1]) {
        print "Client IP " field[3] " is already registered to another peer; refusing to apply" > "/dev/stderr"
        exit 1
      }
    }
  }
'

# A peer already persisted with a DIFFERENT preshared key must not be applied: awg set
# would update the live interface while the file keeps the old block, so the next container
# restart would silently revert the peer to the old key.
awk -v peers_file="$PEERS_FILE" '
  sub(/^PublicKey *= */, "")    { peer = $0; next }
  sub(/^PresharedKey *= */, "") { persisted[peer] = $0; next }
  END {
    while ((getline line < peers_file) > 0) {
      if (split(line, field, " ") != 3) continue
      if (field[1] in persisted && persisted[field[1]] != field[2]) {
        print "Peer " field[1] " is already persisted with a different preshared key; refusing to apply" > "/dev/stderr"
        exit 1
      }
    }
  }
' "$CONFIGURATION_FILE"

while IFS=' ' read -r PUBLIC_KEY PRESHARED_KEY CLIENT_IP || [ -n "$PUBLIC_KEY" ]; do
  [ -n "$PUBLIC_KEY" ] || continue

  printf '%s' "$PRESHARED_KEY" \
    | awg set "$INTERFACE" peer "$PUBLIC_KEY" preshared-key /dev/stdin allowed-ips "$CLIENT_IP/32"

  grep -qF "PublicKey = $PUBLIC_KEY" "$CONFIGURATION_FILE" && continue

  printf '\n[Peer]\nPublicKey = %s\nPresharedKey = %s\nAllowedIPs = %s/32\n' \
    "$PUBLIC_KEY" "$PRESHARED_KEY" "$CLIENT_IP" >> "$CONFIGURATION_FILE"
done < "$PEERS_FILE"
