#!/bin/bash
set -euo pipefail

# Everything this script writes is node state, including the server private key — owner-only.
umask 077

# AmneziaWG server init. Idempotent: if the configuration file exists, only bring the interface up.
# Server keys and obfuscation are generated ONCE and persisted to the state volume; the
# preshared key is per-client and generated at issue time, not here.
# File layout comes from the image ENV (Dockerfile); address and port from the compose environment.

: "${STATE_DIRECTORY:?}" "${INTERFACE:?}" "${CONFIGURATION_FILE:?}" \
  "${SERVER_PRIVATE_KEY_FILE:?}" "${SERVER_PUBLIC_KEY_FILE:?}" \
  "${SERVER_PRIVATE_KEY_SOURCE_FILE:?}" "${SERVER_PUBLIC_KEY:?}" \
  "${OBFUSCATION_FILE:?}" "${MIMICRY_PRESET_FILE:?}" "${ADDRESS:?}" "${PORT:?}"

# Egress interface for NAT. This MASQUERADE runs INSIDE the container, so it must be the
# container's own default-route interface (eth0 on a docker bridge) — NOT the host's interface.
# Detect it at runtime so it's correct regardless of how the host names its NICs.
EGRESS_DEVICE="${EGRESS_DEVICE:-$(ip route show default | awk '/default/ {print $5; exit}')}"
EGRESS_DEVICE="${EGRESS_DEVICE:-eth0}"

mkdir -p "${STATE_DIRECTORY}"

rand_u32() { od -An -N4 -tu4 /dev/urandom | tr -d ' '; }

if [[ ! -f "${CONFIGURATION_FILE}" ]]; then
  # Server keys are generated by @spurro/infrastructure and injected so the node can be
  # reproduced from stored state. The private key arrives as a read-only bind-mounted file
  # (SERVER_PRIVATE_KEY_SOURCE_FILE) — never an env var — so it is not exposed via docker
  # inspect / the compose file; the public key is not secret and arrives via SERVER_PUBLIC_KEY.
  echo "[init] writing injected server keys"
  cat "${SERVER_PRIVATE_KEY_SOURCE_FILE}" > "${SERVER_PRIVATE_KEY_FILE}"
  printf '%s' "${SERVER_PUBLIC_KEY}" > "${SERVER_PUBLIC_KEY_FILE}"

  # Obfuscation: fixed profile from the mimicry preset (Jc/Jmin/Jmax, S1-S4, H1-H4, I1-I5).
  # The obfuscation file is the preset verbatim so every client inherits the exact same profile.
  cp "${MIMICRY_PRESET_FILE}" "${OBFUSCATION_FILE}"
  OBFUSCATION_BLOCK=$(cat "${MIMICRY_PRESET_FILE}")

  # Automatic per-node obfuscation (disabled — using the fixed preset above). To restore
  # random generation, re-enable this block AND write the obfuscation file with WG keys (Jc, not JC).
  # JC=$(( (RANDOM % 9) + 4 ))
  # JMIN=$(( (RANDOM % 193) + 64 ))    # 64..256
  # JMAX=$(( (RANDOM % 513) + 512 ))   # 512..1024
  # S1=$(( RANDOM % 65 ))
  # S2=$(( RANDOM % 65 ))
  # while [[ $(( S1 + 56 )) -eq "${S2}" ]]; do S2=$(( RANDOM % 65 )); done
  # S3=$(( RANDOM % 65 ))
  # S4=$(( RANDOM % 33 ))
  # HBAND=1073741822
  # rand_h_range() {
  #   local start=$(( 5 + $1 * HBAND ))
  #   local lo=$(( start + ($(rand_u32) % (HBAND / 2)) ))
  #   local hi=$(( lo + 1 + ($(rand_u32) % (HBAND / 2)) ))
  #   echo "${lo}-${hi}"
  # }
  # H1=$(rand_h_range 0); H2=$(rand_h_range 1); H3=$(rand_h_range 2); H4=$(rand_h_range 3)

  # Written to a temp file and moved into place: the configuration file only ever exists
  # complete, so a partially written config can never pass the verify branch below.
  echo "[init] writing ${CONFIGURATION_FILE}"
  cat > "${CONFIGURATION_FILE}.tmp" <<EOF
[Interface]
PrivateKey = $(cat "${SERVER_PRIVATE_KEY_FILE}")
Address = ${ADDRESS}
ListenPort = ${PORT}

${OBFUSCATION_BLOCK}

# NAT: client traffic egresses under the server IP
PostUp = iptables -t nat -A POSTROUTING -o ${EGRESS_DEVICE} -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -o ${EGRESS_DEVICE} -j MASQUERADE

# peer isolation: clients can't reach each other
PostUp = iptables -A FORWARD -i %i -o %i -j DROP
PostDown = iptables -D FORWARD -i %i -o %i -j DROP

# block tunnel -> hoster internal networks
PostUp = iptables -A FORWARD -i %i -d 10.0.0.0/8 -j DROP
PostUp = iptables -A FORWARD -i %i -d 172.16.0.0/12 -j DROP
PostUp = iptables -A FORWARD -i %i -d 192.168.0.0/16 -j DROP
PostDown = iptables -D FORWARD -i %i -d 10.0.0.0/8 -j DROP
PostDown = iptables -D FORWARD -i %i -d 172.16.0.0/12 -j DROP
PostDown = iptables -D FORWARD -i %i -d 192.168.0.0/16 -j DROP
EOF
  mv "${CONFIGURATION_FILE}.tmp" "${CONFIGURATION_FILE}"
  echo "[init] server public key: $(cat "${SERVER_PUBLIC_KEY_FILE}")"
else
  echo "[init] existing config found — verifying state matches the deployment"

  # The generated block of the configuration (keys, ListenPort, Address) is written ONCE and
  # never regenerated, so a deployment that changes PORT/ADDRESS silently diverges
  # from the live state. Refuse to start instead: a loud failed deploy beats a half-broken node.
  CONFIGURED_PORT=$(awk -F' *= *' '$1 == "ListenPort" { print $2; exit }' "${CONFIGURATION_FILE}")
  if [[ "${CONFIGURED_PORT}" != "${PORT}" ]]; then
    echo "[verify] state has ListenPort ${CONFIGURED_PORT}, deployment expects ${PORT}; refusing to start" >&2
    exit 1
  fi

  CONFIGURED_ADDRESS=$(awk -F' *= *' '$1 == "Address" { print $2; exit }' "${CONFIGURATION_FILE}")
  if [[ "${CONFIGURED_ADDRESS}" != "${ADDRESS}" ]]; then
    echo "[verify] state has Address ${CONFIGURED_ADDRESS}, deployment expects ${ADDRESS}; refusing to start" >&2
    exit 1
  fi

  CONFIGURED_SERVER_PUBLIC_KEY=$(cat "${SERVER_PUBLIC_KEY_FILE}" 2>/dev/null || true)
  if [[ "${CONFIGURED_SERVER_PUBLIC_KEY}" != "${SERVER_PUBLIC_KEY}" ]]; then
    echo "[verify] state has server public key ${CONFIGURED_SERVER_PUBLIC_KEY:-<missing>}, deployment expects ${SERVER_PUBLIC_KEY}; refusing to start" >&2
    exit 1
  fi
fi

echo "[up] bringing up ${INTERFACE}"
awg-quick up "${CONFIGURATION_FILE}"
awg show

term() { echo "[down] stopping ${INTERFACE}"; awg-quick down "${CONFIGURATION_FILE}" || true; exit 0; }
trap term SIGTERM SIGINT
sleep infinity &
wait $!
